# Change these first
owner: RecapTime
repo: status-page

sites:
  - name: Squad Website
    url: https://recaptime.tk
  - name: Vaultwarden - Self-hosted Public
    url: https://bw.rtapp.tk/alive
  - name: golinks
    url: https://go.rtapp.tk/ping
  - name: Link Shortener Service
    url: https://rtapp.tk
  - name: Squad Wiki
    url: https://wiki.rtapp.tk

status-website:
  cname: status.rtapp.tk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Recap Time Infra Status
  introTitle: "Are we down or we did broke the DNS again?"
  introMessage: "Monitor the uptime of Recap Time's different services, powered by Upptime and GitHub Actions."
  navbar:
    - title: Home
      href: /
    - title: Issue Tracker
      href: https://github.com/$OWNER/$REPO/issues
    - title: Community Lores Status
      href: https://status.community-lores.gq

# Identification purposes on API
user-agent: "RecapTimeBot/0.1.2021 (repo: https://github.com/RecapTime/status-page; integration: upptime)"

# Workflow schedules
workflowSchedule:
  responseTime: "*/10 * * * *"
  staticSite: "*/30 * * * *"
  summary: "0 */1 * * *"
  updateTemplate: "0 0 * * *"
  updates: "*/30 * * * *"
  uptime: "*/15 * * * *"

# git config
commitMessages:
  commitAuthorName: "Recap Time Bot"
  commitAuthorEmail: "service-accounts+github@recaptime.tk"

# Other stuff
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: false

# Issue assignees
assignees:
  - ajhalili2006
  - RecapTimeSquad
