# Change these first
owner: RecapTime
repo: status-page

sites:
  - name: Squad Website
    url: https://recaptime.tk
  - name: Vaultwarden - Self-hosted Public
    url: https://bw.rtapp.tk//alive
  - name: golinks
    url: https://go.rtapp.tk/ping
  - name: Link Shortener Service
    url: https://rtapp.tk

status-website:
  cname: status.rtapp.tk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Recap Time Infra Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: /
    - title: Issue Tracker
      href: https://github.com/$OWNER/$REPO
    - title: Community Lores Status
      href: https://status.community-lores/gq

# Identification purposes on API
user-agent: "RecapTimeBot/0.1.2021 (repo: https://github.com/Community-Lores/status-page; integration: upptime)"

# Workflow schedules
workflowSchedule:
  graphs: "0 */2 * * *"
  responseTime: "*/10 * * * *"
  staticSite: "*/30 * * * *"
  summary: "0 */1 * * *"
  updateTemplate: "0 0 * * *"
  updates: "*/30 * * * *"
  uptime: "*/15 * * * *"

# git config
commitMessages:
  commitAuthorName: "Recap Time Bot"
  commitAuthorEmail: "service-accounts+github@recaptime.tk"

# Other stuff
skipDescriptionUpdate: false
skipTopicsUpdate: true
skipHomepageUpdate: false

# Issue assignees
assignees:
  - ajhalili2006
  - RecapTimeSquad
